-- MySQL Script generated by MySQL Workbench
-- Mon Oct  3 12:07:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema salon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salon` DEFAULT CHARACTER SET utf8mb4 ;
USE `salon` ;

-- -----------------------------------------------------
-- Table `salon`.`Admin-salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salon`.`Admin-salon` (
  `id_salon` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `site` VARCHAR(45) NOT NULL,
  `profile` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_salon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salon`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salon`.`Client` (
  `id_client` INT NOT NULL,
  `  nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `planning_idplanning` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  `Salon_id_salon` INT NOT NULL,
  PRIMARY KEY (`id_client`, `planning_idplanning`, `Salon_id_salon`),
  INDEX `fk_Client_Salon1_idx` (`Salon_id_salon` ASC) ,
  CONSTRAINT `fk_Client_Salon1`
    FOREIGN KEY (`Salon_id_salon`)
    REFERENCES `salon`.`Admin-salon` (`id_salon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salon`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salon`.`Service` (
  `id_service` INT NOT NULL,
  `nom_service` VARCHAR(45) NOT NULL,
  `description_service` VARCHAR(45) NOT NULL,
  `prix` FLOAT NOT NULL,
  `type_service` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salon`.`planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salon`.`planning` (
  `id_planning` INT NOT NULL,
  `date` DATE NOT NULL,
  `heure_debut` TIME NOT NULL,
  `id_Service` INT NOT NULL,
  `Service_id_Service` INT NOT NULL,
  `heure_fin` TIME NOT NULL,
  `Salon_id_salon` INT NOT NULL,
  `Client_id_client` INT NOT NULL,
  PRIMARY KEY (`id_planning`, `Service_id_Service`),
  INDEX `fk_reservation_Service1_idx` (`Service_id_Service` ASC) ,
  INDEX `fk_Reservation_Salon1_idx` (`Salon_id_salon` ASC) ,
  INDEX `fk_planning_Client1_idx` (`Client_id_client` ASC) ,
  CONSTRAINT `fk_reservation_Service1`
    FOREIGN KEY (`Service_id_Service`)
    REFERENCES `salon`.`Service` (`id_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Salon1`
    FOREIGN KEY (`Salon_id_salon`)
    REFERENCES `salon`.`Admin-salon` (`id_salon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planning_Client1`
    FOREIGN KEY (`Client_id_client`)
    REFERENCES `salon`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salon`.`Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salon`.`Employers` (
  `id_employer` INT NOT NULL,
  `employer_nom` VARCHAR(45) NOT NULL,
  `prenom_employer` VARCHAR(45) NOT NULL,
  `adresse_employers` VARCHAR(45) NOT NULL,
  `description-travail` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `planning_id_planning` INT NOT NULL,
  `planning_Service_id_Service` INT NOT NULL,
  PRIMARY KEY (`id_employer`, `planning_id_planning`, `planning_Service_id_Service`),
  INDEX `fk_Employers_planning1_idx` (`planning_id_planning` ASC, `planning_Service_id_Service` ASC) ,
  CONSTRAINT `fk_Employers_planning1`
    FOREIGN KEY (`planning_id_planning` , `planning_Service_id_Service`)
    REFERENCES `salon`.`planning` (`id_planning` , `Service_id_Service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salon`.`Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salon`.`Facture` (
  `id_Facture` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `Details_Facture_id_Details_Facture` INT NOT NULL,
  `Client_id_client` INT NOT NULL,
  `Client_planning_idplanning` INT NOT NULL,
  `Admin-salon_id_salon` INT NOT NULL,
  PRIMARY KEY (`id_Facture`),
  INDEX `fk_Facture_Client1_idx` (`Client_id_client` ASC, `Client_planning_idplanning` ASC) ,
  INDEX `fk_Facture_Admin-salon1_idx` (`Admin-salon_id_salon` ASC) ,
  CONSTRAINT `fk_Facture_Client1`
    FOREIGN KEY (`Client_id_client` , `Client_planning_idplanning`)
    REFERENCES `salon`.`Client` (`id_client` , `planning_idplanning`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facture_Admin-salon1`
    FOREIGN KEY (`Admin-salon_id_salon`)
    REFERENCES `salon`.`Admin-salon` (`id_salon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salon`.`Client_has_Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salon`.`Client_has_Facture` (
  `Client_idClient` INT NOT NULL,
  `Facture_id_Facture` INT NOT NULL,
  PRIMARY KEY (`Client_idClient`, `Facture_id_Facture`),
  INDEX `fk_Client_has_Facture_Facture1_idx` (`Facture_id_Facture` ASC) ,
  INDEX `fk_Client_has_Facture_Client1_idx` (`Client_idClient` ASC) ,
  CONSTRAINT `fk_Client_has_Facture_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `salon`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Facture_Facture1`
    FOREIGN KEY (`Facture_id_Facture`)
    REFERENCES `salon`.`Facture` (`id_Facture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
