-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 13:23:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbsalon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsalon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsalon` DEFAULT CHARACTER SET utf8mb4 ;
USE `dbsalon` ;

-- -----------------------------------------------------
-- Table `dbsalon`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsalon`.`Client` ;

CREATE TABLE IF NOT EXISTS `dbsalon`.`Client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `  nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalon`.`Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsalon`.`Service` ;

CREATE TABLE IF NOT EXISTS `dbsalon`.`Service` (
  `id_service` INT NOT NULL AUTO_INCREMENT,
  `nom_service` VARCHAR(45) NOT NULL,
  `description_service` VARCHAR(45) NOT NULL,
  `prix` FLOAT NOT NULL,
  `type_service` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalon`.`Admin-salon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsalon`.`Admin-salon` ;

CREATE TABLE IF NOT EXISTS `dbsalon`.`Admin-salon` (
  `nom` VARCHAR(45) NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `site` VARCHAR(45) NOT NULL,
  `profile` VARCHAR(45) NOT NULL,
  `telephone` INT NOT NULL,
  PRIMARY KEY (`nom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalon`.`Employers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsalon`.`Employers` ;

CREATE TABLE IF NOT EXISTS `dbsalon`.`Employers` (
  `id_employer` INT NOT NULL AUTO_INCREMENT,
  `employer_nom` VARCHAR(45) NOT NULL,
  `prenom_employer` VARCHAR(45) NOT NULL,
  `adresse_employers` VARCHAR(45) NOT NULL,
  `description-travail` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalon`.`planning`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsalon`.`planning` ;

CREATE TABLE IF NOT EXISTS `dbsalon`.`planning` (
  `id_planning` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `heure_debut` TIME NOT NULL,
  `id_Service` INT NOT NULL,
  `Service_id_Service` INT NOT NULL,
  `heure_fin` TIME NOT NULL,
  `Client_id_client` INT NOT NULL,
  `Admin-salon_nom` VARCHAR(45) NOT NULL,
  `Employers_id_employer` INT NOT NULL,
  PRIMARY KEY (`id_planning`, `Service_id_Service`),
  INDEX `fk_reservation_Service1_idx` (`Service_id_Service` ASC) ,
  INDEX `fk_planning_Client1_idx` (`Client_id_client` ASC) ,
  INDEX `fk_planning_Admin-salon1_idx` (`Admin-salon_nom` ASC) ,
  INDEX `fk_planning_Employers1_idx` (`Employers_id_employer` ASC) ,
  CONSTRAINT `fk_reservation_Service1`
    FOREIGN KEY (`Service_id_Service`)
    REFERENCES `dbsalon`.`Service` (`id_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planning_Client1`
    FOREIGN KEY (`Client_id_client`)
    REFERENCES `dbsalon`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planning_Admin-salon1`
    FOREIGN KEY (`Admin-salon_nom`)
    REFERENCES `dbsalon`.`Admin-salon` (`nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planning_Employers1`
    FOREIGN KEY (`Employers_id_employer`)
    REFERENCES `dbsalon`.`Employers` (`id_employer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalon`.`Facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsalon`.`Facture` ;

CREATE TABLE IF NOT EXISTS `dbsalon`.`Facture` (
  `id_Facture` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `date` DATETIME NULL,
  `Details_Facture_id_Details_Facture` INT NOT NULL,
  `Client_id_client` INT NOT NULL,
  PRIMARY KEY (`id_Facture`),
  INDEX `fk_Facture_Client1_idx` (`Client_id_client` ASC) ,
  CONSTRAINT `fk_Facture_Client1`
    FOREIGN KEY (`Client_id_client`)
    REFERENCES `dbsalon`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalon`.`Client_has_Facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsalon`.`Client_has_Facture` ;

CREATE TABLE IF NOT EXISTS `dbsalon`.`Client_has_Facture` (
  `Client_idClient` INT NOT NULL,
  `Facture_id_Facture` INT NOT NULL,
  PRIMARY KEY (`Client_idClient`, `Facture_id_Facture`),
  INDEX `fk_Client_has_Facture_Facture1_idx` (`Facture_id_Facture` ASC) ,
  INDEX `fk_Client_has_Facture_Client1_idx` (`Client_idClient` ASC) ,
  CONSTRAINT `fk_Client_has_Facture_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `dbsalon`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Facture_Facture1`
    FOREIGN KEY (`Facture_id_Facture`)
    REFERENCES `dbsalon`.`Facture` (`id_Facture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
